# Generated by Django 5.2.5 on 2025-11-18 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_apply_link_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills_extracted",
            field=models.BooleanField(
                default=False,
                help_text="Whether NLP-powered skills have been extracted for this job",
            ),
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(db_index=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        default="cover_letter",
                        help_text="Source of extraction (cover_letter, resume, manual)",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        default=0,
                        help_text="Confidence score (0-10) from NLP extractor",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "user"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["skill_name"],
                "indexes": [
                    models.Index(
                        fields=["user", "skill_name"],
                        name="jobs_candid_user_id_7922a9_idx",
                    ),
                    models.Index(
                        fields=["skill_name"], name="jobs_candid_skill_n_626921_idx"
                    ),
                ],
                "unique_together": {("user", "skill_name", "source")},
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(db_index=True, max_length=200)),
                (
                    "weight",
                    models.IntegerField(
                        default=0,
                        help_text="Importance score from 0-10 based on NLP extraction",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skills",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-weight", "skill_name"],
                "indexes": [
                    models.Index(
                        fields=["job", "weight"], name="jobs_jobski_job_id_22554c_idx"
                    ),
                    models.Index(
                        fields=["skill_name"], name="jobs_jobski_skill_n_747dbb_idx"
                    ),
                ],
                "unique_together": {("job", "skill_name")},
            },
        ),
    ]
